import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components";
import { Provider } from 'react-redux';
import { store } from '@/redux/store';
import { Providers } from "@/redux/Providers";


const inter = localFont({
  src: './fonts/Inter.ttf',
  variable: '--font-inter',
});

const ibmMono = localFont({
  src: './fonts/IBMMono.ttf',
  variable: '--font-geist-mono',
});

const openSans = localFont({
  src: './fonts/OpenSans.ttf',
  variable: '--font-open-sans',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${inter.variable} ${ibmMono.variable} ${openSans.variable}`}>
      <body >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
